/**
 * Generated by scripts/fetch-map-pins.mjs — do not edit by hand.
 *
 * Percentage positions on each region's illustrated map art, derived from
 * Bulbapedia's per-location Town Map images and carried across by an affine
 * fit on a handful of hand-read anchors. `seed-dex.ts` merges curated.ts on
 * top, so any pin placed by hand wins.
 *
 * 320 pins
 */
export const GENERATED_MAP_PINS: Record<string, [number, number]> = {
  "battle-park": [
    72.5,
    25.9
  ],
  "canalave-city": [
    9.1,
    65.6
  ],
  "celestic-town": [
    52.8,
    41
  ],
  "distortion-world": [
    64.4,
    55.6
  ],
  "eterna-city": [
    37.2,
    42.4
  ],
  "eterna-forest": [
    28,
    43.2
  ],
  "fight-area": [
    70.7,
    29.7
  ],
  "floaroma-town": [
    22.6,
    54.3
  ],
  "fuego-ironworks": [
    23.1,
    49
  ],
  "hearthome-city": [
    52.8,
    61.3
  ],
  "iron-island": [
    17.1,
    37.8
  ],
  "jubilife-city": [
    20.2,
    69.1
  ],
  "lake-acuity": [
    39.7,
    6.1
  ],
  "lake-valor": [
    75,
    68.4
  ],
  "lake-verity": [
    10.1,
    76.6
  ],
  "maniac-tunnel": [
    77.1,
    55.7
  ],
  "newmoon-island": [
    21.7,
    11.9
  ],
  "oreburgh-city": [
    33.6,
    68.3
  ],
  "oreburgh-gate": [
    27.9,
    67.2
  ],
  "pal-park": [
    33.8,
    85.5
  ],
  "pastoria-city": [
    64.9,
    75.9
  ],
  "resort-area": [
    88.2,
    33.1
  ],
  "sandgem-town": [
    21.3,
    78.3
  ],
  "sendoff-spring": [
    81.8,
    60.9
  ],
  "sinnoh-pokemon-league": [
    90.7,
    45.7
  ],
  "sinnoh-route-201": [
    16.5,
    78.4
  ],
  "sinnoh-route-202": [
    21.5,
    74.6
  ],
  "sinnoh-route-203": [
    26.7,
    67.2
  ],
  "sinnoh-route-204": [
    22.2,
    61.7
  ],
  "sinnoh-route-205": [
    27.4,
    50.1
  ],
  "sinnoh-route-206": [
    35.5,
    54.4
  ],
  "sinnoh-route-207": [
    36.6,
    63.3
  ],
  "sinnoh-route-208": [
    46,
    63.2
  ],
  "sinnoh-route-209": [
    59.9,
    62
  ],
  "sinnoh-route-210": [
    60.5,
    44.5
  ],
  "sinnoh-route-211": [
    46.2,
    41.1
  ],
  "sinnoh-route-212": [
    53.1,
    74.8
  ],
  "sinnoh-route-213": [
    73.2,
    76
  ],
  "sinnoh-route-214": [
    77.1,
    59.4
  ],
  "sinnoh-route-215": [
    67.8,
    48.1
  ],
  "sinnoh-route-216": [
    40.2,
    26.4
  ],
  "sinnoh-route-217": [
    37.5,
    17.5
  ],
  "sinnoh-route-218": [
    13.8,
    67.3
  ],
  "sinnoh-route-219": [
    21.1,
    82.3
  ],
  "sinnoh-route-221": [
    29.4,
    85.6
  ],
  "sinnoh-route-222": [
    82.7,
    70.1
  ],
  "sinnoh-route-224": [
    95.8,
    40.4
  ],
  "sinnoh-route-225": [
    69.5,
    22.3
  ],
  "sinnoh-route-227": [
    82.8,
    13.4
  ],
  "sinnoh-route-228": [
    85.6,
    22.3
  ],
  "sinnoh-route-229": [
    86.8,
    29.4
  ],
  "sinnoh-sea-route-220": [
    22.5,
    85.7
  ],
  "sinnoh-sea-route-223": [
    90.1,
    56.8
  ],
  "sinnoh-sea-route-226": [
    79.6,
    18.5
  ],
  "sinnoh-sea-route-230": [
    78.7,
    29.5
  ],
  "snowpoint-city": [
    44.6,
    6
  ],
  "solaceon-town": [
    62.8,
    55.6
  ],
  "stark-mountain": [
    83.2,
    7.3
  ],
  "sunyshore-city": [
    91.1,
    68.1
  ],
  "survival-area": [
    72.9,
    18.5
  ],
  "turnback-cave": [
    83.6,
    58.5
  ],
  "twinleaf-town": [
    14.6,
    82.1
  ],
  "valley-windworks": [
    28.5,
    56.1
  ],
  "veilstone-city": [
    76,
    49.9
  ],
  "azalea-town": [
    43.8,
    78.7
  ],
  "bell-tower": [
    40.6,
    31.1
  ],
  "blackthorn-city": [
    67.4,
    32.1
  ],
  "cherrygrove-city": [
    56.5,
    68.8
  ],
  "cianwood-city": [
    19.4,
    62.2
  ],
  "dark-cave": [
    62.2,
    49.1
  ],
  "ecruteak-city": [
    38.7,
    33.1
  ],
  "frontier-access": [
    23.5,
    42.6
  ],
  "goldenrod-city": [
    35.3,
    62
  ],
  "ilex-forest": [
    39.3,
    79.6
  ],
  "johto-route-29": [
    64.3,
    68.5
  ],
  "johto-route-30": [
    57.7,
    58.6
  ],
  "johto-route-31": [
    54.5,
    49.3
  ],
  "johto-route-32": [
    48.2,
    62.5
  ],
  "johto-route-33": [
    49.4,
    79.2
  ],
  "johto-route-34": [
    38.9,
    72.6
  ],
  "johto-route-35": [
    37.9,
    51.5
  ],
  "johto-route-36": [
    41.2,
    44.8
  ],
  "johto-route-37": [
    40.6,
    40.2
  ],
  "johto-route-38": [
    31.8,
    34.8
  ],
  "johto-route-39": [
    27.5,
    36.9
  ],
  "johto-route-42": [
    46.8,
    34.9
  ],
  "johto-route-43": [
    53,
    26.9
  ],
  "johto-route-44": [
    59.8,
    34.3
  ],
  "johto-route-45": [
    67.1,
    51.4
  ],
  "johto-route-46": [
    64.5,
    64.4
  ],
  "johto-route-47": [
    12.5,
    67.6
  ],
  "johto-route-48": [
    10.7,
    60.1
  ],
  "johto-sea-route-40": [
    24.8,
    52.9
  ],
  "johto-sea-route-41": [
    23.8,
    61.5
  ],
  "lake-of-rage": [
    52.4,
    17.2
  ],
  "mahogany-town": [
    53.1,
    34.8
  ],
  "national-park": [
    36.1,
    42.3
  ],
  "new-bark-town": [
    70.5,
    68.3
  ],
  "olivine-city": [
    29.6,
    47
  ],
  "ruins-of-alph": [
    44.4,
    52
  ],
  "slowpoke-well": [
    45.8,
    79.4
  ],
  "sprout-tower": [
    50.2,
    44.6
  ],
  "union-cave": [
    48.6,
    72
  ],
  "violet-city": [
    48.8,
    47.2
  ],
  "whirl-islands": [
    27.3,
    63.3
  ],
  "celadon-city": [
    48.1,
    44.2
  ],
  "cerulean-cave": [
    62.1,
    17.2
  ],
  "cerulean-city": [
    65.1,
    20.4
  ],
  "cinnabar-island": [
    17.5,
    89.4
  ],
  "fuchsia-city": [
    47.9,
    74.2
  ],
  "kanto-route-1": [
    18.4,
    56.3
  ],
  "kanto-route-10": [
    83.6,
    33.8
  ],
  "kanto-route-11": [
    77.8,
    52.4
  ],
  "kanto-route-12": [
    83.3,
    53
  ],
  "kanto-route-13": [
    77.6,
    64.3
  ],
  "kanto-route-14": [
    72,
    73.2
  ],
  "kanto-route-15": [
    61.8,
    76.5
  ],
  "kanto-route-16": [
    36.6,
    47.5
  ],
  "kanto-route-17": [
    34.2,
    62.3
  ],
  "kanto-route-18": [
    36.1,
    77
  ],
  "kanto-route-2": [
    18.9,
    35.4
  ],
  "kanto-route-22": [
    3.9,
    48.2
  ],
  "kanto-route-24": [
    67.7,
    9.7
  ],
  "kanto-route-25": [
    76,
    5.1
  ],
  "kanto-route-3": [
    33,
    18.7
  ],
  "kanto-route-4": [
    50.6,
    17.5
  ],
  "kanto-route-5": [
    61.9,
    29.1
  ],
  "kanto-route-6": [
    61.6,
    46.9
  ],
  "kanto-route-7": [
    56.3,
    41.1
  ],
  "kanto-route-8": [
    75.3,
    40.6
  ],
  "kanto-route-9": [
    76.3,
    22.8
  ],
  "kanto-sea-route-19": [
    44.6,
    86.4
  ],
  "kanto-sea-route-20": [
    31.1,
    88.2
  ],
  "kanto-sea-route-21": [
    17.9,
    76.7
  ],
  "lavender-town": [
    83.5,
    40.4
  ],
  "pallet-town": [
    17.9,
    65.7
  ],
  "pewter-city": [
    21.4,
    15.2
  ],
  "rock-tunnel": [
    83.8,
    22.6
  ],
  "saffron-city": [
    64.5,
    37.9
  ],
  "seafoam-islands": [
    33.8,
    89
  ],
  "vermilion-city": [
    64.2,
    55.7
  ],
  "viridian-city": [
    15.5,
    45
  ],
  "viridian-forest": [
    18.4,
    30.1
  ],
  "abundant-shrine": [
    80.9,
    31.1
  ],
  "accumula-town": [
    97.2,
    80.5
  ],
  "castelia-city": [
    52.4,
    86.4
  ],
  "castelia-sewers": [
    63.2,
    94.8
  ],
  "celestial-tower": [
    16.7,
    25.6
  ],
  "chargestone-cave": [
    11.6,
    53.7
  ],
  "clay-tunnel": [
    25,
    47.2
  ],
  "cold-storage": [
    59.3,
    45.5
  ],
  "desert-resort": [
    48.1,
    64.5
  ],
  "dragonspiral-tower": [
    21.9,
    7.2
  ],
  "driftveil-city": [
    26,
    59.3
  ],
  "driftveil-drawbridge": [
    39.4,
    53.7
  ],
  "entralink": [
    51.7,
    30.6
  ],
  "floccesy-ranch": [
    11.6,
    87.5
  ],
  "floccesy-town": [
    56.5,
    53.3
  ],
  "icirrus-city": [
    25.6,
    16.8
  ],
  "join-avenue": [
    52.1,
    63.4
  ],
  "lentimas-town": [
    89.1,
    18.4
  ],
  "lostlorn-forest": [
    58.2,
    43.8
  ],
  "marvelous-bridge": [
    64.5,
    46.5
  ],
  "mistralton-cave": [
    21.4,
    42.9
  ],
  "mistralton-city": [
    10.6,
    42.5
  ],
  "moor-of-icirrus": [
    31.8,
    8.8
  ],
  "nacrene-city": [
    84,
    66.6
  ],
  "nimbasa-city": [
    52,
    51.8
  ],
  "opelucid-city": [
    51.5,
    9.3
  ],
  "p2-laboratory": [
    89.2,
    94.4
  ],
  "pinwheel-forest": [
    80,
    73.9
  ],
  "plasma-frigate": [
    85.5,
    34.4
  ],
  "poke-transfer-lab": [
    72,
    39.8
  ],
  "relic-castle": [
    44.5,
    65.5
  ],
  "relic-passage": [
    40.2,
    79.2
  ],
  "reversal-mountain": [
    84.8,
    21
  ],
  "seaside-cave": [
    97.7,
    4.9
  ],
  "skyarrow-bridge": [
    65,
    75.7
  ],
  "strange-house": [
    81.2,
    15
  ],
  "striaton-city": [
    95.2,
    63.3
  ],
  "tubeline-bridge": [
    39,
    11.2
  ],
  "twist-mountain": [
    24.8,
    27.7
  ],
  "undella-bay": [
    65.2,
    37
  ],
  "undella-town": [
    92.9,
    18.7
  ],
  "unova-route-1": [
    97.3,
    89.4
  ],
  "unova-route-10": [
    59.3,
    45.5
  ],
  "unova-route-11": [
    56.9,
    7.8
  ],
  "unova-route-12": [
    71.6,
    3.5
  ],
  "unova-route-13": [
    85.1,
    10.2
  ],
  "unova-route-14": [
    85.3,
    31.5
  ],
  "unova-route-15": [
    72.1,
    46
  ],
  "unova-route-16": [
    57.3,
    50.3
  ],
  "unova-route-2": [
    96.4,
    71.8
  ],
  "unova-route-20": [
    16.1,
    94.2
  ],
  "unova-route-3": [
    89.6,
    65
  ],
  "unova-route-4": [
    52.2,
    74
  ],
  "unova-route-5": [
    46.6,
    53.4
  ],
  "unova-route-6": [
    18.2,
    50.7
  ],
  "unova-route-7": [
    18,
    29.6
  ],
  "unova-route-8": [
    31.4,
    15.2
  ],
  "unova-route-9": [
    46.1,
    10.9
  ],
  "unova-victory-road-2": [
    59.3,
    45.5
  ],
  "unova-victory-road": [
    59.3,
    45.5
  ],
  "village-bridge": [
    64,
    4
  ],
  "virbank-city": [
    24.2,
    91.9
  ],
  "wellspring-cave": [
    89.3,
    57.9
  ],
  "abandoned-ship": [
    19.8,
    85.5
  ],
  "ancient-tomb": [
    47.1,
    14.4
  ],
  "desert-ruins": [
    29.7,
    24.5
  ],
  "desert-underpass": [
    13,
    7.5
  ],
  "dewford-town": [
    7.4,
    88
  ],
  "ever-grande-city": [
    94.4,
    41.9
  ],
  "fallarbor-town": [
    13.1,
    9.8
  ],
  "fiery-path": [
    24.5,
    24
  ],
  "fortree-city": [
    44.1,
    4.1
  ],
  "granite-cave": [
    4,
    82.9
  ],
  "hoenn-altering-cave": [
    22,
    52.1
  ],
  "hoenn-route-106": [
    4,
    82.9
  ],
  "hoenn-route-107": [
    14.4,
    86.5
  ],
  "hoenn-route-108": [
    22.8,
    85
  ],
  "hoenn-route-109": [
    28.1,
    78.1
  ],
  "hoenn-route-111": [
    29.8,
    20.2
  ],
  "hoenn-route-112": [
    24.5,
    24
  ],
  "hoenn-route-113": [
    21.6,
    8
  ],
  "hoenn-route-114": [
    6.8,
    15
  ],
  "hoenn-route-115": [
    2.1,
    28.4
  ],
  "hoenn-route-116": [
    10.4,
    37.6
  ],
  "hoenn-route-117": [
    22.3,
    41
  ],
  "hoenn-route-118": [
    37.9,
    38.1
  ],
  "hoenn-route-119": [
    40.1,
    18.4
  ],
  "hoenn-route-120": [
    47.2,
    11.6
  ],
  "hoenn-route-121": [
    55.6,
    18.3
  ],
  "hoenn-route-122": [
    57.1,
    26.3
  ],
  "hoenn-route-123": [
    49.9,
    35.9
  ],
  "hoenn-route-124": [
    76.1,
    20
  ],
  "hoenn-route-125": [
    86.5,
    15.3
  ],
  "hoenn-route-126": [
    73.9,
    37
  ],
  "hoenn-route-127": [
    84.3,
    35.1
  ],
  "hoenn-route-128": [
    85.6,
    45.9
  ],
  "hoenn-route-129": [
    85.5,
    51.4
  ],
  "hoenn-route-130": [
    77.1,
    52.9
  ],
  "hoenn-route-131": [
    66.5,
    54.9
  ],
  "hoenn-route-132": [
    54.4,
    57.1
  ],
  "hoenn-route-133": [
    45.9,
    58.7
  ],
  "hoenn-route-134": [
    35.5,
    60.6
  ],
  "hoenn-safari-zone": [
    57.3,
    18
  ],
  "hoenn-victory-road": [
    94.5,
    38.7
  ],
  "jagged-pass": [
    22.8,
    24.3
  ],
  "lavaridge-town": [
    19.5,
    25.1
  ],
  "lilycove-city": [
    66,
    16.7
  ],
  "littleroot-town": [
    14.8,
    70.1
  ],
  "marine-cave": [
    69.1,
    40
  ],
  "mauville-city": [
    31.1,
    39.7
  ],
  "meteor-falls": [
    2.1,
    28.8
  ],
  "mirage-spot-island": [
    76.9,
    53
  ],
  "mossdeep-city": [
    86.2,
    23.9
  ],
  "new-mauville": [
    29.9,
    46.5
  ],
  "pacifidlog-town": [
    59.8,
    56.3
  ],
  "rusturf-tunnel": [
    10.4,
    37.6
  ],
  "scorched-slab": [
    47.4,
    3.3
  ],
  "seafloor-cavern": [
    83.9,
    46.2
  ],
  "sealed-chamber": [
    39,
    60
  ],
  "shoal-cave": [
    84.3,
    17.8
  ],
  "sky-pillar": [
    66.5,
    54.9
  ],
  "slateport-city": [
    28.6,
    65.1
  ],
  "sootopolis-city": [
    74.1,
    37.2
  ],
  "southern-island": [
    41.8,
    81.5
  ],
  "team-aqua-hideout": [
    68.1,
    16
  ],
  "verdanturf-town": [
    15.6,
    42.4
  ],
  "ambrette-town": [
    25.1,
    72
  ],
  "anistar-city": [
    87.9,
    34.9
  ],
  "azure-bay": [
    30,
    25.3
  ],
  "camphrier-town": [
    42.7,
    54.5
  ],
  "chamber-of-emptiness": [
    70.4,
    56.3
  ],
  "connecting-cave": [
    24.6,
    54.6
  ],
  "coumarine-city": [
    35.9,
    27.5
  ],
  "couriway-town": [
    92.9,
    42.2
  ],
  "cyllage-city": [
    19.9,
    54.2
  ],
  "dendemille-town": [
    68.9,
    27.1
  ],
  "frost-cavern": [
    72.7,
    20.6
  ],
  "geosenge-town": [
    11.5,
    45.1
  ],
  "glittering-cave": [
    38.4,
    71.6
  ],
  "kalos-pokemon-league": [
    74,
    40.2
  ],
  "kalos-route-1": [
    65.8,
    78
  ],
  "kalos-route-10": [
    14.4,
    53.3
  ],
  "kalos-route-11": [
    12.1,
    44.4
  ],
  "kalos-route-12": [
    25.4,
    34.1
  ],
  "kalos-route-13": [
    42,
    34.2
  ],
  "kalos-route-14": [
    51.4,
    23.6
  ],
  "kalos-route-15": [
    59.3,
    21.5
  ],
  "kalos-route-16": [
    60.8,
    34.3
  ],
  "kalos-route-17": [
    77.1,
    34.6
  ],
  "kalos-route-18": [
    89.5,
    42.1
  ],
  "kalos-route-19": [
    87.9,
    50.9
  ],
  "kalos-route-2": [
    65.6,
    67.7
  ],
  "kalos-route-20": [
    82.2,
    65.4
  ],
  "kalos-route-21": [
    78,
    55
  ],
  "kalos-route-22": [
    67.4,
    55.7
  ],
  "kalos-route-3": [
    63.5,
    60
  ],
  "kalos-route-4": [
    56.9,
    48.2
  ],
  "kalos-route-5": [
    46.3,
    48.9
  ],
  "kalos-route-6": [
    35.6,
    51.3
  ],
  "kalos-route-7": [
    32.4,
    57.8
  ],
  "kalos-route-8": [
    21,
    66.9
  ],
  "kalos-route-9": [
    30.5,
    75.7
  ],
  "kalos-victory-road": [
    74.1,
    50.9
  ],
  "kiloude-city": [
    76.1,
    87.3
  ],
  "laverre-city": [
    52.4,
    9.5
  ],
  "lost-hotel": [
    60.2,
    23.4
  ],
  "lumiose-city": [
    53.1,
    34.1
  ],
  "parfum-palace": [
    31.2,
    41.9
  ],
  "poke-ball-factory": [
    52.5,
    4.4
  ],
  "pokemon-village": [
    81.2,
    71
  ],
  "reflection-cave": [
    14.9,
    37.4
  ],
  "santalune-city": [
    62.8,
    53.1
  ],
  "santalune-forest": [
    67.4,
    60.2
  ],
  "sea-spirits-den": [
    26.8,
    16
  ],
  "shalour-city": [
    17.1,
    34.1
  ],
  "snowbelle-city": [
    85.2,
    52.1
  ],
  "terminus-cave": [
    95.9,
    34
  ]
};
