import React from 'react';
import { Link } from 'react-router-dom';
import LegalPage, { LabeledItem, LegalSection } from '../components/LegalPage';

const CONTACT_EMAIL = 'khanhpronam@gmail.com';

const Privacy: React.FC = () => (
  <LegalPage title="Privacy Policy" updated="June 23, 2026">
    <LegalSection n={1} title="Introduction">
      <p>
        Welcome to MasterPokedex. We operate this web application and its API (hereinafter
        referred to as "Service"). This page informs you of our policies regarding the
        collection, use, and disclosure of personal data when you use our Service, and the
        choices you have. The short version: we store the minimum an account needs, we sell
        nothing, and everything else stays on your device.
      </p>
    </LegalSection>

    <LegalSection n={2} title="Definitions">
      <p>
        SERVICE means the MasterPokedex web application and API operated by the maintainer.
      </p>
      <p>
        PERSONAL DATA means data about a living individual who can be identified from that data —
        here, essentially your email address and anything you choose to put on your trainer
        profile.
      </p>
      <p>
        TRAINER DATA means the game-flavored records attached to your account: profile, teams,
        caught Pokémon, bag, favorites, friendships and activity.
      </p>
      <p>
        USAGE DATA is data generated by the use of the Service, such as server logs of API
        requests.
      </p>
      <p>
        LOCAL PREFERENCES are settings stored only in your browser's local storage, such as sprite
        style and theme.
      </p>
    </LegalSection>

    <LegalSection n={3} title="Information We Collect">
      <p>
        Account: your email address and a salted, hashed password, held by our authentication
        provider (Supabase). We never see or store your plaintext password.
      </p>
      <p>
        Profile: the username you claim and whatever you choose to add — display name, bio, avatar
        URL, home region, favorite type. All of it except the username is optional.
      </p>
      <p>
        Trainer Data: teams, caught Pokémon (with nicknames and notes), items, favorites,
        friendships and an activity feed of your in-app actions.
      </p>
    </LegalSection>

    <LegalSection n={4} title="What We Deliberately Do Not Collect">
      <p>
        No payment data (there is nothing to buy). No advertising identifiers. No third-party
        analytics or tracking pixels. No precise location. No contact list access. The map shows
        Kanto, not you.
      </p>
    </LegalSection>

    <LegalSection n={5} title="Use of Data">
      <p>
        We use your data to provide and maintain the Service: to authenticate you, render your
        trainer profile, enforce visibility rules, show your activity to accepted friends, and
        notify you of nothing — see Communications in the{' '}
        <Link to="/terms" className="underline">Terms of Service</Link>.
      </p>
    </LegalSection>

    <LegalSection n={6} title="What Other Users See">
      <p>
        If your profile is public (the default), other users see your username, display name,
        avatar, bio, region, rank, badges, counts, teams and caught Pokémon. If you switch your
        profile to private in your profile settings, only accepted friends see it. Your email
        address is never shown to anyone.
      </p>
    </LegalSection>

    <LegalSection n={7} title="Local Preferences">
      <p>
        Sprite style and theme are stored in your browser's local storage and never leave your
        device. Clearing site data resets them.
      </p>
    </LegalSection>

    <LegalSection n={8} title="Retention of Data">
      <p>
        We retain your Personal Data and Trainer Data for as long as your account exists. When
        your account is deleted, every row attached to it — profile, teams, caught Pokémon, bag,
        friendships, favorites, activity — is deleted with it by database-level cascade, not by a
        cleanup job that might forget something.
      </p>
    </LegalSection>

    <LegalSection n={9} title="Where Data Lives">
      <p>
        Data is stored in a PostgreSQL database hosted by Supabase. Depending on the project
        region, this may be outside your country of residence. By using the Service you consent
        to this transfer; the safeguards in Section 11 travel with it.
      </p>
    </LegalSection>

    <LegalSection n={10} title="Disclosure of Data">
      <p>
        We do not sell, rent, or trade your data — with anyone, for anything. We would disclose
        data only if required by law or to protect the rights or safety of users, and a fan
        Pokédex rarely finds itself in that position.
      </p>
    </LegalSection>

    <LegalSection n={11} title="Security of Data">
      <p>
        No transmission over the Internet is 100% secure, but the architecture is built so the
        blast radius of a mistake is small:
      </p>
      <LabeledItem label="Token Verification">
        every authenticated request is verified against the auth provider's published signing
        keys; the API trusts cryptography, not cookies.
      </LabeledItem>
      <LabeledItem label="Per-User Scoping">
        every query that touches Trainer Data is scoped to the verified user id from the token —
        the request body is never trusted to say whose data it wants.
      </LabeledItem>
      <LabeledItem label="Row Level Security">
        the database enforces the same visibility rules again, so even a path around the API
        hits the same wall.
      </LabeledItem>
      <LabeledItem label="Least Privilege">
        the browser holds only a publishable key; server secrets never ship in the bundle.
      </LabeledItem>
      <LabeledItem label="Validated Input">
        every write is validated against a strict schema; field and operator names in queries
        come from server-side whitelists, never from request strings.
      </LabeledItem>
    </LegalSection>

    <LegalSection n={12} title="Third-Party Services">
      <p>
        Supabase provides authentication and database hosting (see their privacy policy at
        supabase.com/privacy). Pokémon reference data and sprite images are served from PokeAPI
        and its public sprite repository on GitHub; your browser fetches images directly from
        those hosts, which see your IP address the way any image host does. The frontend is
        served from GitHub Pages.
      </p>
    </LegalSection>

    <LegalSection n={13} title="Cookies and Local Storage">
      <p>
        The Service sets no advertising or analytics cookies. The authentication session is kept
        in local storage by the Supabase client so you stay signed in between visits; signing out
        removes it.
      </p>
    </LegalSection>

    <LegalSection n={14} title="AI Training Data">
      <p>
        We do not use your Personal Data or Trainer Data to train AI models, and we do not share
        it with anyone who would. Your shiny Gyarados's nickname stays between you and the
        database.
      </p>
    </LegalSection>

    <LegalSection n={15} title="Your Data Protection Rights">
      <p>
        Wherever you live, we honor the same set of rights: access (ask what we hold about you),
        rectification (fix it — mostly self-service via your profile), erasure (delete your
        account and everything cascades), and portability (ask and we will export your Trainer
        Data in JSON). Contact us at the address below to exercise any of them.
      </p>
    </LegalSection>

    <LegalSection n={16} title="GDPR (European Economic Area)">
      <p>
        If you are in the EEA, the legal basis for processing is the performance of a contract
        (providing the Service you signed up for) and our legitimate interest in keeping it
        secure. You additionally have the right to object, to restrict processing, and to lodge a
        complaint with your local supervisory authority.
      </p>
    </LegalSection>

    <LegalSection n={17} title="California Privacy Rights (CCPA)">
      <p>
        If you are a California resident, you have the right to know what personal information we
        collect (Sections 3 and 4 are the complete list), to request deletion, and to not be
        discriminated against for exercising those rights. We do not sell personal information,
        so there is nothing to opt out of.
      </p>
    </LegalSection>

    <LegalSection n={18} title="Children's Privacy">
      <p>
        The Service is not directed to children under 13 (or the equivalent minimum age in your
        jurisdiction), and we do not knowingly collect data from them. If you believe a child has
        provided us Personal Data, contact us and we will delete the account.
      </p>
    </LegalSection>

    <LegalSection n={19} title="Changes to This Privacy Policy">
      <p>
        We may update this policy from time to time. Changes are posted on this page with an
        updated date at the top; material changes will be called out on the Service itself.
      </p>
    </LegalSection>

    <LegalSection n={20} title="Contact Us">
      <p>
        If you have any questions about this Privacy Policy, please contact us by email:{' '}
        <a href={`mailto:${CONTACT_EMAIL}`} className="underline">
          {CONTACT_EMAIL}
        </a>
        .
      </p>
    </LegalSection>
  </LegalPage>
);

export default Privacy;
